//! Miden-specific pieces of the `miden-p2id-private` x402 scheme.
//!
//! The structures here plug into the network- and scheme-agnostic types from
//! `x402-types`. See [`crate::aliases`] for the composed `PaymentRequirements`
//! and `PaymentPayload` aliases that downstream code should use.
//!
//! Per [`ideas/DESIGN.md`], the only payment kind this protocol carries is a
//! private P2ID note settled by a Guardian-facilitator via verify-before-prove
//! + batched settlement. There is no public-note path, no settled-at-commit
//! path, and no "exact" scheme — those concepts belong to the previous
//! standalone facilitator that this refactor replaces.

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::fmt;

use crate::ids::{AccountIdHex, NoteIdHex};

/// Tag struct that always serialises and deserialises as the JSON string
/// `"miden-p2id-private"`. This is the only scheme this protocol speaks.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct MidenP2idPrivateScheme;

impl MidenP2idPrivateScheme {
    /// The wire representation.
    pub const VALUE: &'static str = "miden-p2id-private";
}

impl fmt::Display for MidenP2idPrivateScheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(Self::VALUE)
    }
}

impl Serialize for MidenP2idPrivateScheme {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(Self::VALUE)
    }
}

impl<'de> Deserialize<'de> for MidenP2idPrivateScheme {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = String::deserialize(deserializer)?;
        if raw == Self::VALUE {
            Ok(MidenP2idPrivateScheme)
        } else {
            Err(serde::de::Error::custom(format!(
                "expected scheme \"{}\", got \"{}\"",
                Self::VALUE,
                raw
            )))
        }
    }
}

/// Contents of the `extra` field on the 402 response.
///
/// Per DESIGN.md, the only two fields carried are `note_tag` (an opaque tag
/// the merchant uses to demultiplex incoming P2ID notes on its side) and
/// `serial_num` (server-generated by the Guardian-facilitator via
/// `POST /x402/challenge`). The merchant inlines the issued `serial_num` so
/// the Guardian can know the future nullifier the moment it emits the 402.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MidenP2idPrivateExtra {
    /// Note-tag the merchant attaches to incoming P2ID notes for routing.
    pub note_tag: String,
    /// Server-issued 32-byte `serial_num` (canonical hex). `None` on the
    /// initial 402-bootstrap call before the merchant has obtained one from
    /// `POST /x402/challenge`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial_num: Option<NoteIdHex>,
}

/// The scheme-specific payload that travels in `PAYMENT-SIGNATURE`.
///
/// Carries:
///
/// - `tx_inputs`: base64 of canonical `miden_protocol::transaction::TransactionInputs`.
///   The Guardian uses this for two things — reading the buyer's
///   `PartialAccount.storage()` for context, and forwarding to the remote
///   prover at settle time.
/// - `signature`: base64 of `miden_protocol::account::auth::Signature` — the
///   buyer's Falcon signature over the tx summary. Sent explicitly (rather
///   than only via the advice map embedded in `tx_inputs`) because the advice
///   map stores a stack-reversed prepared form that cannot be inverted back
///   to the high-level signature needed for offline verification.
/// - `signed_summary`: base64 of `miden_protocol::transaction::TransactionSummary`
///   — the exact value whose `to_commitment()` digest the buyer signed. The
///   facilitator binds this to `tx_inputs` (via input-notes commitment) and to
///   the output P2ID note (via output-notes membership) before verifying the
///   signature.
/// - `expected_note_blob`: base64 of `miden_protocol::note::NoteFile::NoteDetails`
///   for the expected output P2ID note. Used by the facilitator to recompute
///   the recipient/asset binding.
/// - `serial_num`: echo of `extra.serial_num`. Must match the value the
///   facilitator issued and the value baked into `expected_note_blob`.
/// - `sender`, `asset`, `amount`: redundant for fast-fail validation.
///
/// `transaction_id` is intentionally absent — the only meaningful id is the
/// post-prove `ProvenTransaction.id()` that the facilitator returns in
/// `SettleResponse`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MidenP2idPrivatePayload {
    /// Base64-encoded canonical `TransactionInputs`.
    pub tx_inputs: String,
    /// Base64-encoded `Signature` over `signed_summary.to_commitment()`.
    pub signature: String,
    /// Base64-encoded canonical `TransactionSummary`.
    pub signed_summary: String,
    /// Base64-encoded `NoteFile::NoteDetails` for the expected output note.
    pub expected_note_blob: String,
    /// Echo of `extra.serial_num`.
    pub serial_num: NoteIdHex,
    /// Buyer account id (the note's sender).
    pub sender: AccountIdHex,
    /// Faucet account id of the fungible asset being transferred.
    pub asset: AccountIdHex,
    /// Atomic-unit amount as a decimal string (x402 v2 convention).
    pub amount: String,
}

/// Tag wrapper around [`MidenP2idPrivatePayload`] so the wire shape matches
/// the x402 v2 convention of a tagged payload variant. Always serialises with
/// `noteType: "miden-p2id-private"`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "noteType", rename_all = "kebab-case")]
pub enum MidenWirePayload {
    /// The only payload variant — private P2ID via Guardian-facilitator.
    #[serde(rename = "miden-p2id-private")]
    MidenP2idPrivate(MidenP2idPrivatePayload),
}

impl MidenWirePayload {
    /// Returns a reference to the underlying private payload (single-variant
    /// enum; provided so call sites don't have to pattern-match every time).
    pub fn inner(&self) -> &MidenP2idPrivatePayload {
        match self {
            MidenWirePayload::MidenP2idPrivate(p) => p,
        }
    }

    /// Consumes the wrapper and returns the inner payload.
    pub fn into_inner(self) -> MidenP2idPrivatePayload {
        match self {
            MidenWirePayload::MidenP2idPrivate(p) => p,
        }
    }

    /// Returns the buyer (note sender) for the embedded payload — convenience
    /// for echoing into `VerifyResponse::Valid { payer }`.
    pub fn payer(&self) -> &AccountIdHex {
        &self.inner().sender
    }
}

impl From<MidenP2idPrivatePayload> for MidenWirePayload {
    fn from(p: MidenP2idPrivatePayload) -> Self {
        MidenWirePayload::MidenP2idPrivate(p)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_account() -> AccountIdHex {
        "0x0a7d175ed63ec5200fb2ced86f6aa5".parse().unwrap()
    }

    fn sample_word(c: char) -> String {
        format!("0x{}", c.to_string().repeat(64))
    }

    fn sample_payload() -> MidenP2idPrivatePayload {
        MidenP2idPrivatePayload {
            tx_inputs: "AAA=".to_owned(),
            signature: "c2ln".to_owned(),
            signed_summary: "c3VtbWFyeQ==".to_owned(),
            expected_note_blob: "Zm9v".to_owned(),
            serial_num: sample_word('c').parse().unwrap(),
            sender: sample_account(),
            asset: sample_account(),
            amount: "1000".to_owned(),
        }
    }

    #[test]
    fn scheme_serialises_as_kebab_string() {
        let json = serde_json::to_string(&MidenP2idPrivateScheme).unwrap();
        assert_eq!(json, "\"miden-p2id-private\"");
    }

    #[test]
    fn scheme_rejects_unknown_values() {
        let res: Result<MidenP2idPrivateScheme, _> = serde_json::from_str("\"exact\"");
        assert!(res.is_err(), "must not accept legacy `exact` scheme");
    }

    #[test]
    fn extra_serialises_with_camel_case_and_omits_missing_serial_num() {
        let extra = MidenP2idPrivateExtra { note_tag: "abc".to_owned(), serial_num: None };
        let json = serde_json::to_string(&extra).unwrap();
        assert!(json.contains("\"noteTag\":\"abc\""));
        assert!(!json.contains("serialNum"), "missing serial_num should be omitted");
    }

    #[test]
    fn extra_round_trips_with_serial_num() {
        let extra = MidenP2idPrivateExtra {
            note_tag: "abc".to_owned(),
            serial_num: Some(sample_word('c').parse().unwrap()),
        };
        let json = serde_json::to_string(&extra).unwrap();
        let decoded: MidenP2idPrivateExtra = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, extra);
    }

    #[test]
    fn payload_serialises_with_kebab_tag() {
        let wire = MidenWirePayload::from(sample_payload());
        let value = serde_json::to_value(&wire).unwrap();
        assert_eq!(value["noteType"], "miden-p2id-private");
        assert_eq!(value["txInputs"], "AAA=");
        assert_eq!(value["expectedNoteBlob"], "Zm9v");
        assert_eq!(value["amount"], "1000");
        assert!(value.get("blockNum").is_none(), "no block num on the wire");
        assert!(
            value.get("transactionId").is_none(),
            "pre-prove tx id is not part of the wire",
        );
    }

    #[test]
    fn payload_round_trips() {
        let original = MidenWirePayload::from(sample_payload());
        let json = serde_json::to_string(&original).unwrap();
        let decoded: MidenWirePayload = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, original);
    }
}
